version: "3.8"
services:
  web:
    # build: <chemin_vers_dossier_contenant_dockerfile>
    build: .
    volumes:
      - ./src:/app/src
    ports:
      # - <HOST_PORT>:<CONTAINER_PORT>
      - 5000:5000
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
    volumes:
      - hotel_data:/var/lib/mysql

volumes:
  hotel_data:
